[toolchain]

[features]
resolution = true
skip-lint = true

[programs.localnet]
code_vm = "vmZ1WUq8SxjBWcaeTCvgJRZbS84R61uniFsQy5YMRTJ"

[registry]
url = "https://api.apr.dev"

[provider]
wallet = "/Users/johnny/.config/solana/id.json"
cluster = "http://localhost:8899"

[scripts]
test = "echo \"Error: no test specified\" && exit 1"
